export const GET_ERRORS = "GET_ERRORS";
export const GET_INCIDENTS = "GET_INCIDENTS";
export const GET_INCIDENT = "GET_INCIDENT";
export const DELETE_INCIDENT = "DELETE_INCIDENT";

//Types for BACKLOG ACTIONS

export const GET_BACKLOG = "GET_BACKLOG";
export const GET_INCIDENT_TASK = "GET_INCIDENT_TASK";
export const DELETE_INCIDENT_TASK = "DELETE_INCIDENT_TASK";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
